name: Tests

on: push
jobs:
  test:
    strategy:
      matrix:
        python-version: ["3.13"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: 👾 Clone repo to runner
      uses: actions/checkout@v4

    - name: 🐍 Install python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: 🏗️ Install Poetry
      run: |
        pip install poetry
        poetry config virtualenvs.in-project true

    - name: 👀 Check python and poetry versions
      run: |
        python --version
        poetry --version

    - name: 🏗️ Install dependencies using Poetry
      run: poetry install --with dev

    - name: 🤖 Run tests and generate coverage report
      run: |
        source .venv/bin/activate
        pytest --cov=aoc2024 --cov-report=xml

    - name: 📤 Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
